// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWSnHZ0OmegeqBXCW8Jg9Wo_cyO6r7_A',
    appId: '1:1098561015569:web:1fc5098373345ea4fb46b0',
    messagingSenderId: '1098561015569',
    projectId: 'letterai-collection',
    authDomain: 'letterai-collection.firebaseapp.com',
    storageBucket: 'letterai-collection.firebasestorage.app',
    measurementId: 'G-2PGDZM4KJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMK5bit6BuaoctpzvVYPjk9e4T7a-gLBY',
    appId: '1:1098561015569:android:57e01ca84d63e59efb46b0',
    messagingSenderId: '1098561015569',
    projectId: 'letterai-collection',
    storageBucket: 'letterai-collection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vJTawYb7QVraOKUjK83rvwIlTtqjGiw',
    appId: '1:1098561015569:ios:94053f423da58752fb46b0',
    messagingSenderId: '1098561015569',
    projectId: 'letterai-collection',
    storageBucket: 'letterai-collection.firebasestorage.app',
    iosBundleId: 'com.example.letteraiColletion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vJTawYb7QVraOKUjK83rvwIlTtqjGiw',
    appId: '1:1098561015569:ios:94053f423da58752fb46b0',
    messagingSenderId: '1098561015569',
    projectId: 'letterai-collection',
    storageBucket: 'letterai-collection.firebasestorage.app',
    iosBundleId: 'com.example.letteraiColletion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSWSnHZ0OmegeqBXCW8Jg9Wo_cyO6r7_A',
    appId: '1:1098561015569:web:d37404e1c263f764fb46b0',
    messagingSenderId: '1098561015569',
    projectId: 'letterai-collection',
    authDomain: 'letterai-collection.firebaseapp.com',
    storageBucket: 'letterai-collection.firebasestorage.app',
    measurementId: 'G-YKD9E7GXS3',
  );
}
